;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Enemy",DevComment="")
GameplayTagList=(Tag="Enemy.State",DevComment="")
GameplayTagList=(Tag="Enemy.State.Attack",DevComment="")
GameplayTagList=(Tag="Enemy.State.Patrol",DevComment="")
GameplayTagList=(Tag="Enemy.Type",DevComment="")
GameplayTagList=(Tag="Enemy.Type.Boss",DevComment="")
GameplayTagList=(Tag="Enemy.Type.FlyRange",DevComment="")

